apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/argocd/applicationSets
    repoURL: '{{ .Values.repoUrl }}'
    targetRevision: HEAD
  project: 'platform-core'