apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: fargate-profile-tfp
  labels:
    crossplane.io/xrd: xfargateprofiles.upc.tfp.eks
    provider: aws-upbound
spec:
  compositeTypeRef:
    apiVersion: upc.tfp.eks/v1alpha1
    kind: XFargateProfile
  resources:
  - name: fargateprofile
    base:
      apiVersion: eks.aws.upbound.io/v1beta1
      kind: FargateProfile
      metadata:
        name: "fargateprofile" # To be patched
      spec:
        forProvider:
          region: "" #To be patched
          clusterName: "" #To be patched
          selector:
            - namespace: "" # To be patched
          podExecutionRoleArn: "" # To be patched
        providerConfigRef:
          name: default
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.namespace
      toFieldPath: metadata.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.selector[0].namespace
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.env
      toFieldPath: spec.forProvider.clusterName
      transforms:
      - type: map
        map:
          dev: {{ .Values.env.dev.one.cluster }}
          dev2: {{ .Values.env.dev.two.cluster }}
          dev3: {{ .Values.env.dev.three.cluster }}
          qa: {{ .Values.env.qa.one.cluster }}
          prod: {{ .Values.env.prod.one.cluster }}
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.env
      toFieldPath: spec.forProvider.region
      transforms:
      - type: map
        map:
          dev: {{ .Values.env.dev.one.region }}
          dev2: {{ .Values.env.dev.two.region }}
          dev3: {{ .Values.env.dev.three.region }}
          qa: {{ .Values.env.qa.one.region }}
          prod: {{ .Values.env.prod.one.region }}
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.env
      toFieldPath: spec.forProvider.podExecutionRoleArn
      transforms:
      - type: map
        map:
          dev: {{ .Values.env.dev.one.role }}
          dev2: {{ .Values.env.dev.two.role }}
          dev3: {{ .Values.env.dev.three.role }}
          qa: {{ .Values.env.qa.one.role }}
          prod: {{ .Values.env.prod.one.role }}
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.arn
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.status
      toFieldPath: status.status