apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xacmcerts.security.upc.tfp.eks
spec:
  group: security.upc.tfp.eks
  names:
    kind: XACMCert
    plural: xacmcerts
  claimNames:
    kind: ACMCert
    plural: acmcerts
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  domainName:
                    type: string
                  env:
                    type: string
                required:
                - domainName
            required:
            - parameters
          status:
            type: object
            properties:
              arn:
                description: ARN of the ACM Certificate in AWS.
                type: string
              notAfter:
                type: string
              notBefore:
                type: string
              # pendingRenewal:
              #   type: bool
              # renewalEligibility:
              #   type: string
              certStatus:
                description: Status of the ACM Certificate in AWS.
                type: string
              domainValidationOptions:
                type: array
                items:
                  type: object
                  properties:
                    domainName:
                      type: string
                    resourceRecordName:
                      type: string
                    resourceRecordType:
                      type: string
                    resourceRecordValue:
                      type: string
              # Possibility to retrieve all status info from each resource
              # RecordStatus:
              #   type: array
              #   items:
              #     type: object
              #     x-kubernetes-preserve-unknown-fields: true
              # CertValidationStatus:
              #   type: array
              #   items:
              #     type: object
              #     x-kubernetes-preserve-unknown-fields: true
