apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-namespaces
spec:
  generators:
  - git:
      repoURL: https://github.com/scalzadonna/upc-cloud-arch-tfp-apps.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: "{{path.basename}}-namespace"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: "{{path.basename}}"
      source:
        repoURL: https://github.com/scalzadonna/upc-cloud-arch-tfp-infra.git
        targetRevision: HEAD
        path: "helm/namespaces"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{path.basename}}-namespace"
          valueFiles:
            - "../../apps/{{path.basename}}/{{path.basename}}.yaml"
      destination:
        # Default base cluster
        server: 'https://kubernetes.default.svc'
        # name: "default"
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true