apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-projects
spec:
  generators:
  - git:
      repoURL: https://github.com/scalzadonna/upc-cloud-arch-tfp-apps.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: "{{path.basename}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: platform-core
      source:
        repoURL: git@github.com:scalzadonna/upc-cloud-arch-tfp-infra.git
        targetRevision: HEAD
        path: "helm/projects"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{path.basename}}"
          parameters:
            - name: "projectname"
              value: "{{path.basename}}"
      destination:
        # Default base cluster
        server: 'https://kubernetes.default.svc'
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true