apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-platform-core
spec:
  generators:
  - list:
      elements:
      - appSet: crossplane-core
        wave: "-3"
      - appSet: apps-projects
        wave: "-2"
      - appSet: namespaced-apps
        wave: "-1"
  template:
    metadata:
      name: "{{appSet}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        #argocd.argoproj.io/sync-wave: "{{wave}}"
    spec:
      project: "platform-core"
      source:
        repoURL: https://github.com/scalzadonna/upc-cloud-arch-tfp-infra.git
        targetRevision: HEAD
        path: "helm/argocd/{{appSet}}"
      destination:
        # Default base cluster
        server: 'https://kubernetes.default.svc'
        namespace: "platform-core"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true